=== OysterBrain/CQRS-EVENT-SOURCING/PROJET TUTEURÉ/DETAILXML.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="DETAIL" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="DETAIL">
<xsd:annotation>
<xsd:appinfo/>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="faction" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="idTournee" minOccurs="1" od:jetType="autonumber" od:sqlSType="int" od:autoUnique="yes" od:nonNullable="yes" type="xsd:int"/>
<xsd:element name="dateTournee" minOccurs="0" od:jetType="datetime" od:sqlSType="datetime" type="xsd:dateTime"/>
<xsd:element name="heureDepart" minOccurs="0" od:jetType="datetime" od:sqlSType="datetime" type="xsd:dateTime"/>
<xsd:element name="heureArrivee" minOccurs="0" od:jetType="datetime" od:sqlSType="datetime" type="xsd:dateTime"/>
<xsd:element name="tempsTournee" minOccurs="0" od:jetType="datetime" od:sqlSType="datetime" type="xsd:dateTime"/>
<xsd:element name="zone0" minOccurs="0" od:jetType="datetime" od:sqlSType="datetime" type="xsd:dateTime"/>
<xsd:element name="zone1" minOccurs="0" od:jetType="datetime" od:sqlSType="datetime" type="xsd:dateTime"/>
<xsd:element name="zone2" minOccurs="0" od:jetType="datetime" od:sqlSType="datetime" type="xsd:dateTime"/>
<xsd:element name="zone3" minOccurs="0" od:jetType="datetime" od:sqlSType="datetime" type="xsd:dateTime"/>
<xsd:element name="zone4" minOccurs="0" od:jetType="datetime" od:sqlSType="datetime" type="xsd:dateTime"/>
<xsd:element name="zone5" minOccurs="0" od:jetType="datetime" od:sqlSType="datetime" type="xsd:dateTime"/>
<xsd:element name="zone6" minOccurs="0" od:jetType="datetime" od:sqlSType="datetime" type="xsd:dateTime"/>
<xsd:element name="zone7" minOccurs="0" od:jetType="datetime" od:sqlSType="datetime" type="xsd:dateTime"/>
<xsd:element name="zone8" minOccurs="0" od:jetType="datetime" od:sqlSType="datetime" type="xsd:dateTime"/>
<xsd:element name="zone9" minOccurs="0" od:jetType="datetime" od:sqlSType="datetime" type="xsd:dateTime"/>
<xsd:element name="zone10" minOccurs="0" od:jetType="datetime" od:sqlSType="datetime" type="xsd:dateTime"/>
<xsd:element name="zone11" minOccurs="0" od:jetType="datetime" od:sqlSType="datetime" type="xsd:dateTime"/>
<xsd:element name="zone12" minOccurs="0" od:jetType="datetime" od:sqlSType="datetime" type="xsd:dateTime"/>
<xsd:element name="zone13" minOccurs="0" od:jetType="datetime" od:sqlSType="datetime" type="xsd:dateTime"/>
<xsd:element name="zone14" minOccurs="0" od:jetType="datetime" od:sqlSType="datetime" type="xsd:dateTime"/>
<xsd:element name="zone15" minOccurs="0" od:jetType="datetime" od:sqlSType="datetime" type="xsd:dateTime"/>
<xsd:element name="zone16" minOccurs="0" od:jetType="datetime" od:sqlSType="datetime" type="xsd:dateTime"/>
<xsd:element name="zone17" minOccurs="0" od:jetType="datetime" od:sqlSType="datetime" type="xsd:dateTime"/>
<xsd:element name="zone18" minOccurs="0" od:jetType="datetime" od:sqlSType="datetime" type="xsd:dateTime"/>
<xsd:element name="zone19" minOccurs="0" od:jetType="datetime" od:sqlSType="datetime" type="xsd:dateTime"/>
<xsd:element name="zone20" minOccurs="0" od:jetType="datetime" od:sqlSType="datetime" type="xsd:dateTime"/>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== OysterBrain/CQRS-EVENT-SOURCING/PROJET TUTEURÉ/DETAILXML.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="DETAILXML.xsd" generated="2018-11-05T13:27:37">
<DETAIL>
<idTournee>1494</idTournee>
<dateTournee>2018-09-20T00:00:00</dateTournee>
<heureDepart>1899-12-30T23:54:13</heureDepart>
<heureArrivee>1899-12-30T00:34:59</heureArrivee>
<tempsTournee>1899-12-30T00:40:46</tempsTournee>
<zone1>1899-12-30T00:16:37</zone1>
<zone2>1899-12-30T00:00:00</zone2>
<zone3>1899-12-30T00:00:29</zone3>
<zone4>1899-12-30T00:02:52</zone4>
<zone5>1899-12-30T00:01:32</zone5>
<zone6>1899-12-30T00:07:37</zone6>
<zone7>1899-12-30T00:00:19</zone7>
<zone8>1899-12-30T00:01:00</zone8>
<zone9>1899-12-30T00:00:11</zone9>
<zone10>1899-12-30T00:01:29</zone10>
<zone11>1899-12-30T00:00:25</zone11>
<zone12>1899-12-30T00:01:38</zone12>
<zone13>1899-12-30T00:00:38</zone13>
<zone14>1899-12-30T00:02:36</zone14>
<zone15>1899-12-30T00:00:00</zone15>
<zone16>1899-12-30T00:00:06</zone16>
<zone17>1899-12-30T00:01:05</zone17>
<zone18>1899-12-30T00:00:30</zone18>
<zone19>1899-12-30T00:01:37</zone19>
<zone20>1899-12-30T00:00:05</zone20>
</DETAIL>
<DETAIL>
<faction>NUIT</faction>
<idTournee>1495</idTournee>
<dateTournee>2018-09-20T00:00:00</dateTournee>
<heureDepart>1899-12-30T00:35:02</heureDepart>
<heureArrivee>1899-12-30T01:18:28</heureArrivee>
<tempsTournee>1899-12-30T00:43:26</tempsTournee>
<zone1>1899-12-30T00:19:35</zone1>
<zone2>1899-12-30T00:00:00</zone2>
<zone3>1899-12-30T00:00:54</zone3>
<zone4>1899-12-30T00:09:08</zone4>
<zone5>1899-12-30T00:00:00</zone5>
<zone6>1899-12-30T00:00:00</zone6>
<zone7>1899-12-30T00:00:18</zone7>
<zone8>1899-12-30T00:01:06</zone8>
<zone9>1899-12-30T00:00:11</zone9>
<zone10>1899-12-30T00:02:10</zone10>
<zone11>1899-12-30T00:00:20</zone11>
<zone12>1899-12-30T00:03:12</zone12>
<zone13>1899-12-30T00:00:50</zone13>
<zone14>1899-12-30T00:03:43</zone14>
<zone15>1899-12-30T00:00:00</zone15>
<zone16>1899-12-30T00:00:06</zone16>
<zone17>1899-12-30T00:00:22</zone17>
<zone18>1899-12-30T00:00:09</zone18>
<zone19>1899-12-30T00:01:18</zone19>
<zone20>1899-12-30T00:00:04</zone20>
</DETAIL>
<DETAIL>
<faction>NUIT</faction>
<idTournee>1496</idTournee>
<dateTournee>2018-09-20T00:00:00</dateTournee>
<heureDepart>1899-12-30T01:18:31</heureDepart>
<heureArrivee>1899-12-30T02:10:16</heureArrivee>
<tempsTournee>1899-12-30T00:51:45</tempsTournee>
<zone1>1899-12-30T00:26:49</zone1>
<zone2>1899-12-30T00:00:00</zone2>
<zone3>1899-12-30T00:00:24</zone3>
<zone4>1899-12-30T00:00:33</zone4>
<zone5>1899-12-30T00:02:37</zone5>
<zone6>1899-12-30T00:05:20</zone6>
<zone7>1899-12-30T00:00:18</zone7>
<zone8>1899-12-30T00:02:26</zone8>
<zone9>1899-12-30T00:00:22</zone9>
<zone10>1899-12-30T00:00:50</zone10>
<zone11>1899-12-30T00:00:19</zone11>
<zone12>1899-12-30T00:01:51</zone12>
<zone13>1899-12-30T00:06:02</zone13>
<zone14>1899-12-30T00:00:53</zone14>
<zone15>1899-12-30T00:00:00</zone15>
<zone16>1899-12-30T00:00:06</zone16>
<zone17>1899-12-30T00:00:28</zone17>
<zone18>1899-12-30T00:00:34</zone18>
<zone19>1899-12-30T00:01:49</zone19>
<zone20>1899-12-30T00:00:04</zone20>
</DETAIL>
<DETAIL>
<faction>NUIT</faction>
<idTournee>1497</idTournee>
<dateTournee>2018-09-20T00:00:00</dateTournee>
<heureDepart>1899-12-30T02:10:19</heureDepart>
<heureArrivee>1899-12-30T03:04:58</heureArrivee>
<tempsTournee>1899-12-30T00:54:39</tempsTournee>
<zone1>1899-12-30T00:17:23</zone1>
<zone2>1899-12-30T00:00:00</zone2>
<zone3>1899-12-30T00:01:22</zone3>
<zone4>1899-12-30T00:01:14</zone4>
<zone5>1899-12-30T00:04:59</zone5>
<zone6>1899-12-30T00:04:24</zone6>
<zone7>1899-12-30T00:00:18</zone7>
<zone8>1899-12-30T00:05:06</zone8>
<zone9>1899-12-30T00:00:12</zone9>
<zone10>1899-12-30T00:03:54</zone10>
<zone11>1899-12-30T00:00:19</zone11>
<zone12>1899-12-30T00:01:01</zone12>
<zone13>1899-12-30T00:04:01</zone13>
<zone14>1899-12-30T00:03:21</zone14>
<zone15>1899-12-30T00:00:00</zone15>
<zone16>1899-12-30T00:00:05</zone16>
<zone17>1899-12-30T00:01:16</zone17>
<zone18>1899-12-30T00:02:59</zone18>
<zone19>1899-12-30T00:02:41</zone19>
<zone20>1899-12-30T00:00:04</zone20>
</DETAIL>
<DETAIL>
<faction>NUIT</faction>
<idTournee>1498</idTournee>
<dateTournee>2018-09-20T00:00:00</dateTournee>
<heureDepart>1899-12-30T03:05:02</heureDepart>
<heureArrivee>1899-12-30T03:47:42</heureArrivee>
<tempsTournee>1899-12-30T00:42:40</tempsTournee>
<zone1>1899-12-30T00:11:18</zone1>
<zone2>1899-12-30T00:00:00</zone2>
<zone3>1899-12-30T00:02:40</zone3>
<zone4>1899-12-30T00:00:35</zone4>
<zone5>1899-12-30T00:04:58</zone5>
<zone6>1899-12-30T00:03:11</zone6>
<zone7>1899-12-30T00:00:18</zone7>
<zone8>1899-12-30T00:04:48</zone8>
<zone9>1899-12-30T00:00:11</zone9>
<zone10>1899-12-30T00:02:40</zone10>
<zone11>1899-12-30T00:00:19</zone11>
<zone12>1899-12-30T00:01:02</zone12>
<zone13>1899-12-30T00:02:21</zone13>
<zone14>1899-12-30T00:02:35</zone14>
<zone15>1899-12-30T00:00:00</zone15>
<zone16>1899-12-30T00:00:06</zone16>
<zone17>1899-12-30T00:00:17</zone17>
<zone18>1899-12-30T00:02:33</zone18>
<zone19>1899-12-30T00:02:44</zone19>
<zone20>1899-12-30T00:00:04</zone20>
</DETAIL>
<DETAIL>
<faction>NUIT</faction>
<idTournee>1499</idTournee>
<dateTournee>2018-09-20T00:00:00</dateTournee>
<heureDepart>1899-12-30T03:49:05</heureDepart>
<heureArrivee>1899-12-30T04:32:19</heureArrivee>
<tempsTournee>1899-12-30T00:43:14</tempsTournee>
<zone1>1899-12-30T00:22:00</zone1>
<zone2>1899-12-30T00:00:00</zone2>
<zone3>1899-12-30T00:01:12</zone3>
<zone4>1899-12-30T00:00:33</zone4>
<zone5>1899-12-30T00:02:33</zone5>
<zone6>1899-12-30T00:02:44</zone6>
<zone7>1899-12-30T00:00:18</zone7>
<zone8>1899-12-30T00:05:39</zone8>
<zone9>1899-12-30T00:00:11</zone9>
<zone10>1899-12-30T00:00:23</zone10>
<zone11>1899-12-30T00:00:19</zone11>
<zone12>1899-12-30T00:02:21</zone12>
<zone13>1899-12-30T00:00:00</zone13>
<zone14>1899-12-30T00:02:25</zone14>
<zone15>1899-12-30T00:00:00</zone15>
<zone16>1899-12-30T00:00:06</zone16>
<zone17>1899-12-30T00:00:22</zone17>
<zone18>1899-12-30T00:00:31</zone18>
<zone19>1899-12-30T00:01:33</zone19>
<zone20>1899-12-30T00:00:04</zone20>
</DETAIL>
<DETAIL>
<faction>NUIT</faction>
<idTournee>1500</idTournee>
<dateTournee>2018-09-20T00:00:00</dateTournee>
<heureDepart>1899-12-30T04:32:22</heureDepart>
<heureArrivee>1899-12-30T06:12:29</heureArrivee>
<tempsTournee>1899-12-30T01:40:07</tempsTournee>
<zone1>1899-12-30T00:41:23</zone1>
<zone2>1899-12-30T00:00:00</zone2>
<zone3>1899-12-30T00:05:48</zone3>
<zone4>1899-12-30T00:00:34</zone4>
<zone5>1899-12-30T00:03:47</zone5>
<zone6>1899-12-30T00:04:29</zone6>
<zone7>1899-12-30T00:00:28</zone7>
<zone8>1899-12-30T00:06:38</zone8>
<zone9>1899-12-30T00:00:00</zone9>
<zone10>1899-12-30T00:00:00</zone10>
<zone11>1899-12-30T00:00:00</zone11>
<zone12>1899-12-30T00:06:45</zone12>
<zone13>1899-12-30T00:01:29</zone13>
<zone14>1899-12-30T00:25:55</zone14>
<zone15>1899-12-30T00:00:00</zone15>
<zone16>1899-12-30T00:00:06</zone16>
<zone17>1899-12-30T00:00:12</zone17>
<zone18>1899-12-30T00:01:19</zone18>
<zone19>1899-12-30T00:01:10</zone19>
<zone20>1899-12-30T00:00:04</zone20>
</DETAIL>
<DETAIL>
<faction>MATIN</faction>
<idTournee>1501</idTournee>
<dateTournee>2018-09-20T00:00:00</dateTournee>
<heureDepart>1899-12-30T06:12:33</heureDepart>
<heureArrivee>1899-12-30T06:55:10</heureArrivee>
<tempsTournee>1899-12-30T00:42:37</tempsTournee>
<zone1>1899-12-30T00:04:23</zone1>
<zone2>1899-12-30T00:00:00</zone2>
<zone3>1899-12-30T00:09:14</zone3>
<zone4>1899-12-30T00:00:34</zone4>
<zone5>1899-12-30T00:02:07</zone5>
<zone6>1899-12-30T00:03:48</zone6>
<zone7>1899-12-30T00:00:18</zone7>
<zone8>1899-12-30T00:01:58</zone8>
<zone9>1899-12-30T00:00:00</zone9>
<zone10>1899-12-30T00:00:00</zone10>
<zone11>1899-12-30T00:00:00</zone11>
<zone12>1899-12-30T00:05:01</zone12>
<zone13>1899-12-30T00:00:59</zone13>
<zone14>1899-12-30T00:05:40</zone14>
<zone15>1899-12-30T00:00:00</zone15>
<zone16>1899-12-30T00:00:13</zone16>
<zone17>1899-12-30T00:00:12</zone17>
<zone18>1899-12-30T00:06:55</zone18>
<zone19>1899-12-30T00:01:11</zone19>
<zone20>1899-12-30T00:00:04</zone20>
</DETAIL>
<DETAIL>
<faction>MATIN</faction>
<idTournee>1502</idTournee>
<dateTournee>2018-09-20T00:00:00</dateTournee>
<heureDepart>1899-12-30T06:55:14</heureDepart>
<heureArrivee>1899-12-30T07:27:32</heureArrivee>
<tempsTournee>1899-12-30T00:32:18</tempsTournee>
<zone1>1899-12-30T00:03:16</zone1>
<zone2>1899-12-30T00:00:00</zone2>
<zone3>1899-12-30T00:03:53</zone3>
<zone4>1899-12-30T00:00:35</zone4>
<zone5>1899-12-30T00:02:22</zone5>
<zone6>1899-12-30T00:02:52</zone6>
<zone7>1899-12-30T00:00:18</zone7>
<zone8>1899-12-30T00:01:55</zone8>
<zone9>1899-12-30T00:00:00</zone9>
<zone10>1899-12-30T00:00:00</zone10>
<zone11>1899-12-30T00:00:00</zone11>
<zone12>1899-12-30T00:02:12</zone12>
<zone13>1899-12-30T00:04:05</zone13>
<zone14>1899-12-30T00:03:12</zone14>
<zone15>1899-12-30T00:00:00</zone15>
<zone16>1899-12-30T00:00:06</zone16>
<zone17>1899-12-30T00:00:13</zone17>
<zone18>1899-12-30T00:05:48</zone18>
<zone19>1899-12-30T00:01:27</zone19>
<zone20>1899-12-30T00:00:04</zone20>
</DETAIL>
<DETAIL>
<faction>MATIN</faction>
<idTournee>1503</idTournee>
<dateTournee>2018-09-20T00:00:00</dateTournee>
<heureDepart>1899-12-30T07:28:40</heureDepart>
<heureArrivee>1899-12-30T08:16:28</heureArrivee>
<tempsTournee>1899-12-30T00:47:48</tempsTournee>
<zone1>1899-12-30T00:09:19</zone1>
<zone2>1899-12-30T00:00:00</zone2>
<zone3>1899-12-30T00:00:00</zone3>
<zone4>1899-12-30T00:00:34</zone4>
<zone5>1899-12-30T00:02:50</zone5>
<zone6>1899-12-30T00:07:26</zone6>
<zone7>1899-12-30T00:00:20</zone7>
<zone8>1899-12-30T00:02:07</zone8>
<zone9>1899-12-30T00:00:00</zone9>
<zone10>1899-12-30T00:00:00</zone10>
<zone11>1899-12-30T00:00:00</zone11>
